language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xctool clean build test -project JSQNotificationObserverKit/JSQNotificationObserverKit.xcodeproj -scheme JSQNotificationObserverKit -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
- bash <(curl -s https://codecov.io/bash)
