osx_image: xcode7

language: objective-c

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool

script:
- xctool clean build test -project JSQNotificationObserverKit/JSQNotificationObserverKit.xcodeproj -scheme JSQNotificationObserverKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
